import 'dart:convert';
import 'dart:developer';
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:file_saver/file_saver.dart';
import 'package:file_saver/file_saver_web.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:graphical_abstract/helper/api_helper.dart';
import 'package:graphical_abstract/helper/message_helper.dart';
import 'package:graphical_abstract/view/elements/button.dart';
import 'package:file_saver/src/models/file.model.dart';
import 'package:htmltopdfwidgets/htmltopdfwidgets.dart' as HTMLToPdf;
import 'package:pdf/widgets.dart' as pw;
import 'package:markdown/markdown.dart' as md;
import 'package:html/parser.dart' show parse;

class GraphicalAbstractViewModel with ChangeNotifier {
  FilePickerResult? graphicalAbstractFile;
  bool isLoading = false;
  bool isError = false;
  String? errorMessage;
  String writtenAbstract = "";
  String? result;
  ScrollController scrollController = ScrollController();

  void pickGraphicalAbstractFile() async {
    var picked = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ["jpg", "jpeg", "png"]);

    if (picked != null) {
      graphicalAbstractFile = picked;
      notifyListeners();
    } else {
      log("No file selected");
    }
  }

  void onWrittenAbstractChanged(String value) {
    writtenAbstract = value;
    notifyListeners();
  }

  Future<String> getImageAsBase64() async {
    // Get the file path
    String? filePath;
    Uint8List? fileBytes;
    String? imageFormat;
    if (kIsWeb) {
      // Get file type from bytes
      // Note* file.path doesn't work on web
      imageFormat = graphicalAbstractFile!.files[0].name.split(".").last;
    } else {
      filePath = graphicalAbstractFile!.files[0].path!;
      fileBytes = File(filePath).readAsBytesSync();
      imageFormat = filePath.split(".").last;
    }

    // Read the file bytes

    // Get base64 string from the file bytes

    var base64Image = base64Encode(kIsWeb ? graphicalAbstractFile!.files[0].bytes! : fileBytes!);

    // Build the data URI with the detected image format
    var dataUri = "data:image/$imageFormat;base64,$base64Image";

    return dataUri;
  }

  Future<void> copyResultToClipboard(BuildContext context) async {
    if (result != null) {
      await Clipboard.setData(ClipboardData(text: result!));
      // Show a snackbar
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Copied to clipboard"), backgroundColor: Colors.green));
    }
  }

  Future<void> createPDFFromResult() async {
    final pdf = pw.Document();

    final nodes = md.markdownToHtml(result!, extensionSet: md.ExtensionSet.gitHubFlavored);
    var document = parse(nodes);
    // print full html document
    List<pw.Widget> widgets = await HTMLToPdf.HTMLToPdf().convert(document.outerHtml);
    List<pw.Widget> addOnWidgets = [
      // Heading
      pw.Header(
        level: 2,
        textStyle: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
        child: pw.Text(
          "Graphical Abstract Review Report",
          textAlign: pw.TextAlign.center,
          style: const pw.TextStyle(fontSize: 20).copyWith(fontWeight: pw.FontWeight.bold, fontBold: pw.Font.ttf(await rootBundle.load("assets/arial.ttf")), font: pw.Font.ttf(await rootBundle.load("assets/arial.ttf")), fontBoldItalic: pw.Font.ttf(await rootBundle.load("assets/arial.ttf")), fontItalic: pw.Font.ttf(await rootBundle.load("assets/arial.ttf"))),
        ),
      ),
      //* Gap
      pw.SizedBox(height: 25),
      // Add image
      pw.Image(
        height: 300,
        width: 300,
        pw.MemoryImage(kIsWeb ? graphicalAbstractFile!.files[0].bytes! : File(graphicalAbstractFile!.files[0].path!).readAsBytesSync()),
      ),
      pw.SizedBox(height: 25),
    ];

    pdf.addPage(
      pw.MultiPage(
        theme: pw.ThemeData.withFont(
          base: pw.Font.ttf(await rootBundle.load("assets/times_new_roman.ttf")),
          bold: pw.Font.ttf(await rootBundle.load("assets/times_new_roman_bold.ttf")),
          italic: pw.Font.ttf(await rootBundle.load("assets/times_new_roman_italic.ttf")),
          boldItalic: pw.Font.ttf(await rootBundle.load("assets/times_new_roman_bold_italic.ttf")),
        ),
        build: (pw.Context context) {
          return [...addOnWidgets, ...widgets];
        },
        footer: (pw.Context context) {
          return pw.Container(
            alignment: pw.Alignment.centerRight,
            margin: const pw.EdgeInsets.only(top: 1.0 * HTMLToPdf.PdfPageFormat.cm),
            // Link to our website
            child: pw.Link(destination: "https://labcanvas.io", child: pw.Text("Generated by labcanvas.io", style: const pw.TextStyle(fontSize: 10).copyWith(fontWeight: pw.FontWeight.bold))),
          );
        },
      ),
    );

    // Save
    final bytes = await pdf.save();

    if (kIsWeb == false) {
      FileSaver.instance.saveFile(
        name: 'graphical-abstract-review-report',
        file: File.fromRawPath(bytes),
        ext: 'pdf',
        mimeType: MimeType.custom,
        customMimeType: "application/pdf",
      );
    } else {
      FileSaverWeb.downloadFile(
        FileModel(
          name: 'graphical-abstract-review-report',
          bytes: bytes,
          ext: 'pdf',
          mimeType: "application/pdf",
        ),
      );
    }
  }

  void analyzeGraphicalAbstract(BuildContext context) async {
    notifyListeners();
    if (graphicalAbstractFile == null || graphicalAbstractFile!.files.isEmpty || writtenAbstract.isEmpty || writtenAbstract == "") {
      AlertBox.showAlert(
        context,
        title: graphicalAbstractFile == null || graphicalAbstractFile!.files.isEmpty ? "No graphical abstract" : "No written abstract",
        message: graphicalAbstractFile == null || graphicalAbstractFile!.files.isEmpty ? "Please select a graphical abstract to analyze it." : "Please add your written abstract to analyze it",
        fistButtonTitle: "OK",
        onFirstButtonPressed: () => Navigator.pop(context),
      );
    } else {
      try {
        isLoading = true;
        Object response = await API.post(
          "https://api.openai.com/v1/chat/completions",
          body: {
            "model": "gpt-4-vision-preview",
            "messages": [
              {
                "role": "system",
                "content": [
                  {
                    "type": "text",
                    "text": """You are a highly knowledgeable scientific image analysis expert with deep knowledge in graphic design and scientific illustration. Your task is to examine the following image in detail. The image is a graphical abstract of a research paper. Analyze user prompt. It gives the context and details about the research paper. You need to make sure that the message in user prompt is effectively communicated with clarity in graphical abstract. Give suggestions to improve the typography, colors, composition, layout, infomration density, readbility and clarity. We want to optimize this for effectiveness of communication. & user may provide written abstract for the paper.

                    IMPORTANT:
                    Your output should be in valid markdown format & Do't use ### ( no need to use heading tags )""",
                  },
                  {
                    "type": "image_url",
                    "image_url": {
                      "url": await getImageAsBase64(),
                      "detail": "high",
                    }
                  }
                ]
              },
              {
                "role": "system",
                "content": [
                  {"type": "text", "text": writtenAbstract},
                  {
                    "type": "image_url",
                    "image_url": {
                      "url": await getImageAsBase64(),
                      "detail": "high",
                    }
                  }
                ]
              },
            ],
            "max_tokens": 3000,
          },
        );

        if (response is Success) {
          print(response.data);
          result = response.data["choices"][0]["message"]["content"];
          log(result!);
        } else {
          errorMessage = "Something went wrong!";
          isError = true;
        }

        isLoading = false;
        notifyListeners();
        if (result != null) {
          // Scroll little bit down
          scrollController.animateTo(570, duration: const Duration(milliseconds: 500), curve: Curves.easeInOut);
        }
      } catch (e) {
        log(e.toString());
        errorMessage = e.toString();
        isError = true;
        isLoading = false;
        notifyListeners();
      }
    }
  }

  void reset(BuildContext context) {
    AlertBox.showAlert(context,
        title: "Stat over?",
        message: "Are you sure you want to that over again?",
        fistButtonTitle: "Reset",
        firstButtonType: ButtonType.primary,
        onFirstButtonPressed: () {
          graphicalAbstractFile = null;
          isLoading = false;
          isError = false;
          errorMessage = null;
          writtenAbstract = "";
          result = null;
          scrollController = ScrollController();
          notifyListeners();

          Navigator.pop(context);
        },
        secondButtonTitle: "Cancel",
        onSecondButtonPressed: () => Navigator.pop(context));
  }
}
